spring.application.name=backend
spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/eventpass_db
spring.datasource.username=eventpass_user
spring.datasource.password=eventpass_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080